feat: added google social login/register
ispp-2324-ocial/frontend pull request #122
Opened 2024-03-30 17:33 UTC by adrrf

En la pantalla de login se ha añadido un boton que registra/inicia sesión con google (solo usuarios)

2024-03-30 19:42 UTC, ferferga requested changes
Qué orígines has puesto en la consola de Google?

![image](https://github.com/ispp-2324-ocial/frontend/assets/10274099/72f49a5a-8d40-4e2d-989c-b2d541be76f8)

2024-03-30 20:10 UTC, adrrf commented
> Qué orígines has puesto en la consola de Google?
> 
> ![image](https://github.com/ispp-2324-ocial/frontend/assets/10274099/72f49a5a-8d40-4e2d-989c-b2d541be76f8)
> 

localhost:3000, la de despliegue local (sin docker)

2024-04-01 09:37 UTC, ferferga requested changes
Aparte de los errores de lint:

2024-04-01 09:37 UTC, ferferga commented on src/pages/login/index.vue
> +  }));
Aquí habría que pasarle como opción al composable un { skipCache: { request: true }} porque es una solicitud atómica que no se beneficia del estado y no necesita cachearse.

```suggestion
  const { data: UserCreated } = await useApi(UsersApi, 'usersUserGoogleOauth2Create')(() => ({
      googleSocialAuth: {
        'auth_token': credential,
      }
  }));
```

2024-04-01 19:37 UTC, fravilpae approved these changes
Funciona

2024-04-01 19:37 UTC, Jeszamgue approved these changes
Funciona

2024-04-01 19:38 UTC, merged