PR/166 eventos destacados
ispp-2324-ocial/frontend pull request #191
Opened 2024-04-21 16:31 UTC by Ramguerom

2024-04-21 21:10 UTC, ferferga requested changes
3 tonterías

2024-04-21 21:10 UTC, ferferga commented on src/pages/client/events/[id]/edit.vue
> +    await useApi(EventApi, 'eventPartialUpdate')(() => ({
```suggestion
    await useEvent(EventApi, 'eventPartialUpdate')(() => ({
```

2024-04-21 21:10 UTC, ferferga commented on src/pages/client/events/create.vue
>            defaultLatitude: 0,
No tiene nada q ver con tu PR, pero si puedes borrar esto te lo agradezco pq ya no hace falta

2024-04-21 21:10 UTC, ferferga commented on src/components/Layout/LMap.vue
> +
Un poco más conciso

```suggestion
      const customIcon = icon({
        iconUrl: event.highlighted ? Dorado : customIconUrl,
        iconSize: event.highlighted ? [30, 42] : [22, 30],
        iconAnchor: [11, 6]
      });
```

2024-04-21 21:25 UTC, adrrf commented on src/pages/client/events/[id]/edit.vue
> +    await useApi(EventApi, 'eventPartialUpdate')(() => ({
se cambia creo en la de los toast

2024-04-22 09:16 UTC, ferferga commented on src/pages/client/events/[id]/edit.vue
> +const subsEnum = [TypeSubscriptionEnum.Free, TypeSubscriptionEnum.Basic, TypeSubscriptionEnum.Pro ];
```suggestion
const { data : currentSubscription } = await useApi(SubscriptionApi, 'subscriptionRetrieve')();
const subsEnum = [TypeSubscriptionEnum.Free, TypeSubscriptionEnum.Basic, TypeSubscriptionEnum.Pro];
```

2024-04-22 09:17 UTC, ferferga commented on src/pages/client/events/[id]/edit.vue
> +    await useApi(EventApi, 'eventPartialUpdate')(() => ({
No

2024-04-22 09:19 UTC, ferferga commented on src/pages/client/events/create.vue
> +const subsEnum = [TypeSubscriptionEnum.Free, TypeSubscriptionEnum.Basic, TypeSubscriptionEnum.Pro ];
```suggestion
const { data : currentSubscription } = await useApi(SubscriptionApi, 'subscriptionRetrieve')();
const subsEnum = [TypeSubscriptionEnum.Free, TypeSubscriptionEnum.Basic, TypeSubscriptionEnum.Pro];
```

2024-04-22 09:20 UTC, ferferga approved these changes

2024-04-22 09:25 UTC, merged