PR/6
ispp-2324-ocial/frontend pull request #45
Opened 2024-02-29 23:10 UTC by horgarler

2024-03-09 12:13 UTC, ferferga requested changes

2024-03-09 12:13 UTC, ferferga commented on src/layouts/login.vue
> +<!-- eslint-disable @intlify/vue-i18n/no-raw-text -->
```suggestion
```

Con el vídeo del otro día, esto ya lo puedes quitar y arreglar ;)

2024-03-09 12:13 UTC, ferferga commented on src/layouts/login.vue
> +}
Este selector dudo que funcione ya que usas ``scoped``. O lo mueves al CSS global, o lo eliminas si no sirve.

2024-03-09 12:13 UTC, ferferga commented on src/layouts/login.vue
> +  </svg>
Esto quizás podríamos tenerlo en otro componente por si lo queremos reutilizar en otra parte (véase la página de registro, por ejemplo).

2024-03-11 18:36 UTC, closed without merging

2024-03-11 18:39 UTC, horgarler commented
El contenido de esta PR está integrada en la PR 36. Se cierra esta dado que se arreglan varios errores de esta en dicha PR