feat/35: Componente Notificador
ispp-2324-ocial/frontend pull request #47
Opened 2024-03-01 14:42 UTC by paupenfer1

2024-03-01 19:25 UTC, ferferga commented
Esto me temo q no es lo que hace falta. Renderiza un elemento sin más, pero no podemos pasarle nuestro propio mensaje de error desde el formulario y no aparece en una esquina o similares (cambia la distribucion entera de la página al no estar posicionado con position:absolute) :/

Mirate la otra librería que te puse en el issue original (no la de shadcn) para que entiendas mejor el contexto, y añadela al proyecto si hace falta (nadie ha dicho q no puedas usarla!)

Cualquier cosa me preguntas, aunque hasta el sabado por la tarde no voy a poder en condiciones.

2024-03-01 19:26 UTC, ferferga requested changes
Esto me temo q no es lo que hace falta. Renderiza un elemento sin más, pero no podemos pasarle nuestro propio mensaje de error desde el formulario y no aparece en una esquina o similares (cambia la distribucion entera de la página al no estar posicionado con position:absolute) :/

Mirate la otra librería que te puse en el issue original (no la de shadcn) para que entiendas mejor el contexto, y añadela al proyecto si hace falta (nadie ha dicho q no puedas usarla!)

Cualquier cosa me preguntas, aunque hasta el sabado por la tarde no voy a poder en condiciones.

2024-03-09 11:38 UTC, ferferga requested changes
@paupenfer1 No tienes bien instaladas todas las extensiones recomendadas o algo falla en tu entorno de trabajo, porque si te fijas fallan un montón de comprobaciones en tus archivos que a la hora de guardar se deberían de corregir automáticamente (o en su defecto hacerlo a mano pasando el ``npm run check`` para ver cuáles son los errores y ``npm run lint-fix`` para corregirlos).

Para simplificarte trabajo, elimina el ``AlertWarning`` (que solo es un componente que has creado para ver la apariencia del notificador) y ``alertPrueba`` y corrige el resto de errores en los archivos. Además, mira los otros comentarios que te pongo

2024-03-09 11:42 UTC, ferferga requested changes
@paupenfer1 No tienes bien instaladas todas las extensiones recomendadas o algo falla en tu entorno de trabajo, porque si te fijas fallan un montón de comprobaciones en tus archivos que a la hora de guardar se deberían de corregir automáticamente (o en su defecto hacerlo a mano pasando el ``npm run check`` para ver cuáles son los errores y ``npm run lint-fix`` para corregirlos).

Para simplificarte trabajo, elimina el ``AlertWarning`` (que solo es un componente que has creado para ver la apariencia del notificador) y ``alertPrueba`` y corrige el resto de errores en los archivos. Además, resuelve también las otras cuestiones que te pongo en los demás comentarios.

2024-03-09 11:42 UTC, ferferga commented on src/composables/use-toast.ts
> +export const notify = (type: string) => {
Crea un tipo que indique los posibles valores de cadenas que esta función acepta en vez de pasarle el genérico ``string``. Tipo así:

```
type NotificationTypes = 'warning' | 'default' ...
```

2024-03-09 11:42 UTC, ferferga commented on src/composables/use-toast.ts
> +      });
El texto que la notificación muestre debe de pasarse como parámetro de la función. Si algo falla en la validación del formulario de registro, mostrar ``"Error notification !"`` es poco indicativo de cuál es el problema.

2024-03-09 11:42 UTC, ferferga commented on src/main.ts
> +
```suggestion
```

2024-03-09 11:47 UTC, ferferga commented on tsconfig.json
> +      "vue3-toastify/global"
Por qué?

2024-03-09 12:25 UTC, paupenfer1 commented
He eliminado el AlertWarning y alertPrueba y he completado el use-toast con las indicaciones dadas. Pasando el npm run check no me ha dado ningún error.

2024-03-09 12:27 UTC, ferferga commented on src/composables/use-toast.ts
> +      toast.success('Success Notification !' || message, {
Como te dice SonarCloud, las condiciones que has puesto no son correctas, pues el operador de la izquierda siempre es verdadero al estar definido

Inviértelas y usa ?? en vez de ||. ?? sirve solo para valores nulos o no definidos, con || solo seguramente se queje el SonarCloud también porque no es tan estricto.

2024-03-09 12:58 UTC, ferferga requested changes
Una última cosa que se me ha olvidado Paula, lo siento 😅.

Mírate el último vídeo que subí a Discord para traducir los textos de la aplicación. Básicamente tienes que meter dentro del cuerpo de la función el ``const { t } = usei18n()`` y añadir las claves traducidas en cada idioma.

Una vez esté hecho eso ya está todo completo, yo arreglo los conflictos de los package.json

2024-03-09 16:36 UTC, paupenfer1 commented
El ejemplo del video es dentro de un div, como se debería hacer dentro de la función de notify?

2024-03-09 17:07 UTC, ferferga commented
@paupenfer1 Al final explico justo eso, es lo mismo dentro de un ``script setup`` que en cualquier otra parte, es TypeScript.

2024-03-09 17:23 UTC, ferferga requested changes

2024-03-09 17:23 UTC, ferferga commented on src/composables/use-toast.ts
> +const { t } = useI18n();
Esto tiene que estar dentro de notify, en tiempo de ejecución esto suelta error.

2024-03-09 17:49 UTC, merged