feat/32 - mapa
ispp-2324-ocial/frontend pull request #49
Opened 2024-03-01 18:49 UTC by AitorRD

Resuelve la isse #32

2024-03-09 17:04 UTC, AitorRD commented on src/components/LMap.vue
> +          userLocationMarker.bindPopup('Tu ubicación');
He resuelto este cambio en el [commit](https://github.com/ispp-2324-ocial/frontend/pull/49/commits/3bfed0822fab9a42953e5d200f98d82ac375ae7f).

2024-03-09 17:04 UTC, AitorRD commented on src/components/LMap.vue
> +          userLocationMarker.bindPopup('Tu ubicación');
El problema sigue siendo el error en el async

2024-03-11 17:23 UTC, AitorRD commented on src/components/LMap.vue
> +      // eslint-disable-next-line promise/prefer-await-to-callbacks
Esta se ha añadido para corregir el error de lint que daba en esta función, puesto que no era un error per se, simplemente te recomendaba hacer uso de promises y async lo cual acarreaba más warnings de los que se podía solucionar.

2024-03-11 19:27 UTC, ferferga commented on src/components/LMap.vue
> +      // eslint-disable-next-line promise/prefer-await-to-callbacks
@AitorRD El problema era efectivamente del linter, sin embargo, mágicamente le ha gustado al añadir la opción de HighAccuracy (la vi el otro día en la documentación de MDN y se me olvidó decírtelo, pero para nuestro caso es estrictamente necesario) 😁.

2024-03-11 19:30 UTC, ferferga requested changes
Mira si todo funciona bien con mis últimos cambios (se te olvidó sacar el instanciamiento del mapa fuera del callback, y he eliminado algunos console.log, es lo único extra además de añadir el highAccuracy que he cambiado).

Y por último (y ya con esto prometo que va todo para dentro 🙏), en vez de utilizar console.error para los errores, utiliza el notificador que ha hecho @paupenfer1, así si el usuario no ha dado permisos de acceso a la ubicación o ha habido cualquier tipo de error se lo mostramos, y no se lo ocultamos de forma opaca.

2024-03-11 23:44 UTC, ferferga approved these changes

2024-03-11 23:44 UTC, ferferga commented on src/components/LMap.vue
> +        }
Esta lógica está mal, en sucesivas iteraciones siempre evaluará a false y no actualizará la posición en el mapa.

Lo arreglo en mi push para terminar ya este PR, lo he testeado a mano, si hay cualquier otro problema manda un PR con un hotfix

2024-03-11 23:51 UTC, ferferga approved these changes

2024-03-11 23:51 UTC, merged