PR/36
ispp-2324-ocial/frontend pull request #51
Opened 2024-03-04 15:27 UTC by horgarler

2024-03-08 09:28 UTC, adrrf requested changes
hay un commit de merge, hay que arreglarlo

2024-03-08 15:05 UTC, adrrf commented
Todo ok en tema diseño, cuando metamos el back, hay que hacer que los botones para usuarios/clientes lleven a sitios distintos

2024-03-08 15:06 UTC, adrrf approved these changes

2024-03-09 12:14 UTC, ferferga commented
Este PR hace obsoleto a #45? O ese tiene que mergearse antes de este?

2024-03-11 19:26 UTC, Ramguerom reviewed
Lo veo todo correcto

2024-03-12 00:16 UTC, ferferga requested changes
Aparte de las cosas que te menciono aquí, para el sprint 3 apúntate/acuérdate de refactorizar un poco los estilos/elementos utilizados (lo puede hacer otra persona, y de hecho creo que es lo mejor):

* Muchos de los estilos ya te los da el propio Tailwind/UnoCSS hechos pero los re-declaras una y otra vez.
* Hay ciertos elementos que no actúan como deben (por ejemplo, algunos div son botones). Visualmente funcionan, pero a la hora de enfocar (usando tabulador o manteniendo en dispositivos sin punteros finos como móviles), lectores de pantalla, etc... No funcionan bien y no son accesibles.

Estos requisitos no son bloqueantes (solo los de los comentarios individuales), pero para que los tengas en cuenta para sucesivas iteraciones, no me puedo quejar mucho del trabajazo que hay aquí :)

2024-03-12 00:16 UTC, ferferga commented on src/layouts/login.vue
> +  </svg>
(Esto creo que lo comenté en el otro PR) Estaría bien tener esto como un componente aparte para poder reutilizarlo si es necesario, además de dejar componentes no tan monstruosos.

2024-03-12 00:16 UTC, ferferga commented on src/layouts/login.vue
> +display: flex;
```suggestion
  display: flex;
```

Esto lo debería de coger el linter, pero por alguna razón no lo hace, sorry 😅

2024-03-12 15:21 UTC, horgarler commented on src/pages/client/createEvent.vue
> +<!-- eslint-disable vue/require-v-for-key -->
Muchas gracias, esto se solucionará en la próxima PR de la nueva rama

2024-03-12 15:23 UTC, horgarler commented on src/pages/client/events.vue
> +    image: '@/assets/images/temp/yoga.png'
Esto está como placeholder hasta que no pueda trabajar con backend, pero muchas gracias, lo tendré en cuenta para futuros recursos

2024-03-12 21:21 UTC, ferferga requested changes

2024-03-12 22:36 UTC, ferferga approved these changes

2024-03-12 22:38 UTC, merged