hotfix/map
ispp-2324-ocial/frontend pull request #73
Opened 2024-03-12 19:13 UTC by AitorRD

Este hotfix se ha creado para arreglar:
- El problema de muchos marcadores de ubicación en pantalla
- Reiteración del método setView (la vista del mapa se centraba en el usuario continuamente)
- Que el mapa reaccione si se han dado los permisos de ubicación

2024-03-12 19:32 UTC, ferferga requested changes

2024-03-12 19:32 UTC, ferferga commented on src/components/LMap.vue
> +const locationAccess = usePermission('microphone');
```suggestion
const locationAccess = usePermission('geolocation');
```

No? 😆

Si te da error de tipos, prueba de todas maneras a ver si en tiempo de ejecución detecta bien el watcher los cambios que das en la autorización y ya intento yo hacer un PR a la librería para arreglar los tipos.

2024-03-15 11:13 UTC, ferferga requested changes
Ahora la experiencia de usuario es maravillosa y mucho más predecible, olé 😎

Me he dado cuenta por cierto de que estuvimos empanados el primer día y VueUse [incluye un composable como el ``usePermission`` para la geolocalización que incluye datos de altitud, velocidad, etc](https://vueuse.org/core/useGeolocation/#usegeolocation) 😅.

Si quieres, puedes refactorizar el código para usarlo (internamente el composable se encarga de llamar al ``clearWatch`` al desmontar el componente, pedir los permisos, etc), pero no es un *blocker* para mí ni mucho menos, para la funcionalidad que vamos a utilizar nosotros (al menos de momento) es más que suficiente.

Te detallo ahora los cambios que si me gustaría que hicieras:

2024-03-15 11:13 UTC, ferferga commented on src/components/LMap.vue
> +});
```suggestion
}, { immediate: true });
```

https://vuejs.org/guide/essentials/watchers.html#eager-watchers

Por defecto, los watchers de Vue al registrarse no se ejecutan hasta que no suceda el primer cambio en el objeto (a partir de ahí ya también con todos los sucesivos). Esta opción hace que el callback se ejecute nada más se registre el watcher (es decir, también antes del primer cambio)

En nuestro caso, funciona porque si te fijas [en el código fuente del ``usePermission``](https://github.com/vueuse/vueuse/blob/main/packages/core/usePermission/index.ts#L86), el ``ref`` interno que maneja se inicializa en blanco (undefined) y luego se actualiza dentro de una Promesa, por lo que nuestro watcher lo coge y el componente aparece correctamente.

Pero esto podría no ser así en algún momento (imagínate que la librería VueUse actualiza el código de forma que el ref interno que ellos manejan no se inicialice vacío), entonces dejaría de funcionar. Para evitar regresiones (y como sabemos de antemano que este watcher se debe de ejecutar al inicializarse el componente), mejor marcarlo como inmediato.

2024-03-16 13:48 UTC, AitorRD commented
> Ahora la experiencia de usuario es maravillosa y mucho más predecible, olé 😎
> 
> Me he dado cuenta por cierto de que estuvimos empanados el primer día y VueUse [incluye un composable como el `usePermission` para la geolocalización que incluye datos de altitud, velocidad, etc](https://vueuse.org/core/useGeolocation/#usegeolocation) 😅.
> 
> Si quieres, puedes refactorizar el código para usarlo (internamente el composable se encarga de llamar al `clearWatch` al desmontar el componente, pedir los permisos, etc), pero no es un _blocker_ para mí ni mucho menos, para la funcionalidad que vamos a utilizar nosotros (al menos de momento) es más que suficiente.
> 
> Te detallo ahora los cambios que si me gustaría que hicieras:
> 
> El mapInitialized no tiene utilidad ninguna, ya tienes el `mapInstance.value` para comprobar si la instancia de leaflet existe o no, y tampoco es como el marcador del usuario, del que si necesitas un guard en el callback para no mover el visor de la posición.

Lo que comentas de la refactorización lo dejaría para otro momento ya que esto es un hotfix para arreglar el problema del setView y las id

2024-03-16 13:50 UTC, AitorRD commented on src/components/LMap.vue
> +let mapInitialized = false;
Perfecto he sustituido esa variable por el checkeo del mapInstance.value y funciona igual así que si era redundante :thumbsup:

2024-03-16 13:51 UTC, AitorRD commented on src/components/LMap.vue
> +    createMapLayer();
El disposeWatcher tenía mis mis dudas pero creo que lo he implementado correctamente y se limpian (resetean) las id

2024-03-16 13:51 UTC, AitorRD commented on src/components/LMap.vue
> +});
Lo añadido al watch de location pues

2024-03-17 09:29 UTC, ferferga requested changes

2024-03-17 09:29 UTC, ferferga commented on src/components/LMap.vue
> +  disposeMarkers();
```suggestion
  disposeWatcher();
  disposeMarkers();
  disposeMap();
```

Tenemos que hacerlo en este orden para estar 100% seguros de que no haya condiciones de carrera y se ejecute una actualización del mapa o de los marcadores después de hacer el dispose del mapa, lo que daría problemas.

2024-03-17 10:19 UTC, AitorRD commented on src/components/LMap.vue
> +  disposeMarkers();
El cambio lo he añadido a este [commit](https://github.com/ispp-2324-ocial/frontend/pull/73/commits/bb1ff4aa3020ecc0c3eb52a502bdaf0822a5dc7c)

2024-03-17 15:20 UTC, ferferga approved these changes

2024-03-17 15:24 UTC, merged