Feat/52 registro cliente usuario
ispp-2324-ocial/frontend pull request #86
Opened 2024-03-16 12:29 UTC by Ramguerom

2024-03-17 16:34 UTC, ferferga reviewed
Supongo que esto todavía es WIP, pero voy dejando algunas cositas

2024-03-17 16:34 UTC, ferferga commented on src/pages/client/createEvent.vue
> +    <div style="margin-top: 10%; justify-content: center; display: flex;">
Intentad utilizar las clases [``mt-x``](https://unocss.dev/interactive/?s=mt), están preparadas para mantener las proporciones correctamente y nos van a quitar tela de trabajo cuando adaptemos la aplicación al formato móvil.

2024-03-17 16:34 UTC, ferferga commented on src/pages/client/createEvent.vue
> +      style="margin-top: 5%;display: flex;"
Igual

2024-03-17 16:34 UTC, ferferga commented on src/pages/client/editEvent.vue
Igual en todo este archivo

2024-03-17 16:34 UTC, ferferga commented on src/pages/client/events.vue
> +              <p
Igual (pero con sus equivalentes)

2024-03-17 17:20 UTC, ferferga commented on src/pages/client/createEvent.vue
> +    <div style="margin-top: 10%; justify-content: center; display: flex;">
Colocad tambien el tipo de input correcto para cada dato, existe un ``type="date"```en el navegador que ya os da un date picker.

2024-03-19 13:04 UTC, ferferga requested changes

2024-03-19 13:04 UTC, ferferga commented on src/pages/login/registerClient.vue
> +import { useRouter } from 'vue-router';
```suggestion
import { useRouter } from 'vue-router/auto';
```

Actualiza también el resto de importaciones de los archivos de este PR porfa.

Tengo que forzar a nivel de linter esto, pero al importar el ``auto``, utilizamos la versión de Vue Router que tiene type checking y te autocompleta las rutas y los parámetros y todo con TypeScript.

Es un poco mierda el tener que acordarse de esto (por eso voy a intentar forzarlo a nivel de linter) pero el type checking de las rutas ahora mismo es experimental en la librería que utilizamos y esto es lo que hay 🤦‍♂️

2024-03-19 22:19 UTC, Ramguerom commented on src/pages/login/registerClient.vue
> +      type="dni"
Esto del DNI se realizará cuando se conecte a la API, en la Issue #85. Lo realizarán @fravilpae y @Jeszamgue

2024-03-20 13:12 UTC, ferferga requested changes
Faltan todavía los v-for de los inputs y la traducción de los placeholder

2024-03-20 15:51 UTC, ferferga requested changes

2024-03-20 15:51 UTC, ferferga commented on src/pages/login/registerClient.vue
Faltan estos placeholder por traducir

2024-03-20 15:51 UTC, ferferga commented on src/pages/login/register.vue
Faltan estos placeholder por traducir

2024-03-25 10:43 UTC, ferferga approved these changes

2024-03-25 10:44 UTC, merged