Feat/77 event popup
ispp-2324-ocial/frontend pull request #92
Opened 2024-03-18 22:11 UTC by AitorRD

Añadidio:

- Integración con la API del backend
- Añadido el popup del evento con datos y enlace a detalles

2024-03-19 13:15 UTC, ferferga requested changes

2024-03-19 13:15 UTC, ferferga commented on src/components/LMap.vue
> +console.log(eventList.value);
```suggestion
```

2024-03-19 13:15 UTC, ferferga commented on src/components/LMap.vue
> +    }
Esto quizás mejor usar ``console.error`` para que no pete el componente entero (o manejar la excepción en alguna otra parte de forma ``elegantemente``)

2024-03-19 13:15 UTC, ferferga commented on src/components/LMap.vue
> +  [CategoryEnum.NUMBER_4]: Amarillo
(Para que lo sepas, no bloqueante) Ahora mismo en back está arreglado ya (necesito que se mergee https://github.com/ispp-2324-ocial/backend/pull/56 para que sea 100% automático)

Cuando se actualice, CategoryEnum tendrá las categorías reales y no ``NUMBER_X``

2024-03-19 13:15 UTC, ferferga commented on src/components/LMap.vue
> +      const category = event.category === undefined ? CategoryEnum.NUMBER_0 : getCategoryEnum(event.category.toString());
Aquí igual en vez de tener esto, puedes hacer que el parámetro ``categoryName`` sea opcional ``(categoryName?: string)`` y en default devuelves el CategoryEnum.NUMBER_O.

2024-03-19 13:15 UTC, ferferga commented on src/components/LMap.vue
> +        .bindPopup(popupContent);
Esto no hay alguna otra forma en Leaflet de saberlo mediante una clase o algo?

Podríamos envolver todo esto con Teleport:
https://vuejs.org/guide/built-ins/teleport.html#teleport

Y cuando un usuario abra un popup, activar el Teleport al elemento del popup que sea.

2024-03-19 13:15 UTC, ferferga commented on src/components/LMap.vue
> +const { data: eventList } = await useEvent(EventApi, 'eventListList')();
Si ya hacemos el fetch de los datos en el componente padre, por qué es necesario repetirlo aquí?

2024-03-19 22:05 UTC, AitorRD commented on src/components/LMap.vue
> +        .bindPopup(popupContent);
He añadido he importado ahora un Popup del propio leaflet que se puede añadir y cambiar cuando añadamos las valoraciones se me ocurre

2024-03-20 13:06 UTC, ferferga requested changes

2024-03-20 13:06 UTC, ferferga commented on src/components/LMap.vue
> +      `;
Todo esto debe de estar gestionado por Vue, no manual. Hay que extraer la lógica de los popups, de forma que solo pueda haber un marcador activo en todo el mapa y no ilimitados.

* Guarda en un array todos los marcadores que tenga el mapa y si están activos o inactivos
* Haz un computed que te derive si uno de los marcadores está activo
* Haz que el div en el template se monte (``v-if``) si dicho computed devuelve verdadero
* Usa template refs para acceder al elemento: https://vuejs.org/guide/essentials/template-refs.html#template-refs
* Crea un watcher que trackee dicho ref (de esta forma sabes si está montado/desmontado correctamente): https://vuejs.org/guide/essentials/template-refs.html#template-refs
* Cuando dicho watcher sea verdadero, el ref lo aplicas al popup, cuando sea falso, lo eliminas y ya tienes toda la lógica del popup extraída

Como te puse en los otros comentarios, otra opcion es usar Teleport.

Aunque este hilo no tiene solución (porque el que lo publicó no sabía que el montaje/desmontaje de los componentes de Vue es asíncrono y por eso necesitas un watcher), aquí tienes más idea: https://stackoverflow.com/questions/72548373/using-a-vue3-component-as-a-leaflet-popup

2024-03-28 18:57 UTC, ferferga submitted a review, later dismissed
@AitorRD Lo mergeo ya pero falta:

* Adaptar nuevos cambios en la API (concretamente lo de la fecha)
* Hacer referencia a la ruta final correcta de la página de detalles de eventos
* Extraer la lógica de obtener la ubicación a una **store**, haré un issue sobre eso más tarde.

2024-03-28 19:25 UTC, ferferga approved these changes

2024-03-28 19:25 UTC, merged